### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by enbyspiders** [tinypalace/tinypalace-festival#3]
- [ ] Impressum text final machen
- [ ] safer spaces
- [ ] großes logo/aufmacher
- [ ] index seite layout? (alle infos auf einer seite?)
- [ ] blog layout
- [ ] runde bilder?
- [ ] about text
- [ ] translate!!
- [ ] newsletter?

**Comment by enbyspiders** [comment]
moved to tinypalace.github.io
